export const tournamentChannels = [
    {
        id: 1,
        name: "Main Tournament Stream",
        url: "https://youtube.com/channel/NAG-IronmanYT",
        subscribers: "250K",
        description: "Official NAG IronmanYT tournament broadcasts and live updates",
        thumbnail: "https://images.unsplash.com/photo-1577720643272-265f434885b4?w=400&h=300&fit=crop",
        platform: "YouTube",
    },
    {
        id: 2,
        name: "BGMI Pro League",
        url: "https://twitch.tv/bgmiproleague",
        subscribers: "185K",
        description: "Competitive BGMI tournaments and pro team matches",
        thumbnail: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop",
        platform: "Twitch",
    },
    {
        id: 3,
        name: "Gaming Elite",
        url: "https://youtube.com/channel/GamingElite",
        subscribers: "420K",
        description: "Premium gaming content and tournament highlights",
        thumbnail: "https://images.unsplash.com/photo-1538481143081-fd900b3f2debf?w=400&h=300&fit=crop",
        platform: "YouTube",
    },
];

export const tournamentVideos = [
    {
        id: 1,
        title: "BGMI Championship Finals - Ep. 1",
        channelId: 1,
        url: "https://youtube.com/watch?v=dQw4w9WgXcQ",
        duration: "2:45:00",
        views: "125K",
        uploadedAt: "2 days ago",
        thumbnail: "https://images.unsplash.com/photo-1577720643272-265f434885b4?w=400&h=300&fit=crop",
    },
    {
        id: 2,
        title: "Top 10 Clutch Moments - Tournament 2026",
        channelId: 1,
        url: "https://youtube.com/watch?v=RealVideo1",
        duration: "12:35",
        views: "89.5K",
        uploadedAt: "3 days ago",
        thumbnail: "https://images.unsplash.com/photo-1578925078519-91597b0b2edd?w=400&h=300&fit=crop",
    },
    {
        id: 3,
        title: "NAG Team Preparation - Behind the Scenes",
        channelId: 1,
        url: "https://youtube.com/watch?v=RealVideo2",
        duration: "18:20",
        views: "56.2K",
        uploadedAt: "5 days ago",
        thumbnail: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400&h=300&fit=crop",
    },
    {
        id: 4,
        title: "Pro League Tournament Day 1 Highlights",
        channelId: 2,
        url: "https://twitch.tv/videos/RealTwitchVideo1",
        duration: "1:32:00",
        views: "42.8K",
        uploadedAt: "1 day ago",
        thumbnail: "https://images.unsplash.com/photo-1603480033192-082d6919d3e1?w=400&h=300&fit=crop",
    },
    {
        id: 5,
        title: "IronmanYT Interview - Tournament Strategy",
        channelId: 1,
        url: "https://youtube.com/watch?v=RealVideo3",
        duration: "24:15",
        views: "73.1K",
        uploadedAt: "1 week ago",
        thumbnail: "https://images.unsplash.com/photo-1598050108023-dffb3c3d1742?w=400&h=300&fit=crop",
    },
    {
        id: 6,
        title: "Gaming Elite - Tournament Analysis",
        channelId: 3,
        url: "https://youtube.com/watch?v=RealVideo4",
        duration: "28:45",
        views: "95.6K",
        uploadedAt: "3 days ago",
        thumbnail: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&h=300&fit=crop",
    },
];

export const tournamentStats = {
    totalTeams: 128,
    registeredPlayers: 512,
    tournamentDays: 7,
    totalPrizePool: "₹50,00,000",
    channels: 3,
    totalVideos: 24,
    averageViewers: "12.5K",
};

export const registrationData = {
    teamName: "NAG Elite Squad",
    captain: "IronmanYT",
    registrationDate: "Jan 15, 2026",
    status: "Confirmed",
    players: [
        {
            id: 1,
            name: "IronmanYT",
            role: "Captain",
            characterId: "IronmanYT#8394",
            phone: "+91 98765 43210",
        },
        {
            id: 2,
            name: "Pro Gamer",
            role: "Player",
            characterId: "ProGamer#5123",
            phone: "+91 98765 43211",
        },
        {
            id: 3,
            name: "Elite Shot",
            role: "Player",
            characterId: "EliteShot#2891",
            phone: "+91 98765 43212",
        },
        {
            id: 4,
            name: "Shadow Strike",
            role: "Player",
            characterId: "ShadowStrike#7634",
            phone: "+91 98765 43213",
        },
    ],
    nextMatch: {
        date: "Jan 25, 2026",
        time: "18:00 IST",
        opponent: "Phoenix Warriors",
        map: "Erangle",
    },
};
